### PR TITLE
README: fix typo

### PR DESCRIPTION
**Pull request by aldot**
s/inteded/intended/

### CODE REVIEW

**Comment by geky** [comment]
Ah! Thanks for the fix

**Comment by geky** [comment]
Hi @aldot, sorry to bother you twice about this, but we're looking at changing the littlefs-fuse license to BSD in addition to the core littlefs repo (more info here https://github.com/ARMmbed/littlefs/issues/59). It would help to have the license's in sync.

Snce it looks like this was just a typo fix, I don't believe this is blocking the change. But just to let you know we'll be updating the license in this pull request https://github.com/ARMmbed/littlefs-fuse/pull/10. Let us know if you're ok with this change or have any issues with it.

**Comment by aldot** [comment]
On Tue, 10 Jul 2018 at 18:17, Christopher Haster <notifications@github.com>
wrote:

> Hi @aldot <https://github.com/aldot>, sorry to bother you twice about
> this, but we're looking at changing the littlefs-fuse license to BSD in
> addition to the core littlefs repo (more info here ARMmbed/littlefs#59
> <https://github.com/ARMmbed/littlefs/issues/59>). It would help to have
> the license's in sync.
>
> Snce it looks like this was just a typo fix, I don't believe this is
> blocking the change. But just to let you know we'll be updating the license
> in this pull request #10
> <https://github.com/ARMmbed/littlefs-fuse/pull/10>. Let us know if you're
> ok with this change or have any issues with it.
>

Ok for me to change the license to BSD.
Sorry for the delay, been swamped at work.
cheers,

**Comment by geky** [comment]
No worries, thanks for responding

**Pull request merged**
